### ISSUE TITLE
e2e tests for Events is failing

### ISSUE THREAD

**Issue by shazron** [adobe/aio-e2e-tests#36]
This worked previously.
Run log: https://github.com/adobe/aio-e2e-tests/pull/32/checks?check_run_id=2202968463

Might be related to integration/workspace changes.

```
2021-03-26T15:19:53.7074715Z     EventsSDKError: [EventsSDK:ERROR_DELETE_REGISTRATION] Error: 404 - Not Found (https://api.adobe.io/events/organizations/***/integrations/***/registrations/undefined)
2021-03-26T15:19:53.7076057Z 
2021-03-26T15:19:53.7076844Z       539 |         .catch(err => {
2021-03-26T15:19:53.7077816Z       540 |           this.__maskAuthData(sdkDetails)
2021-03-26T15:19:53.7079065Z     > 541 |           reject(new ErrorCode({ sdkDetails, messageValues: err }))
2021-03-26T15:19:53.7080119Z           |                  ^
2021-03-26T15:19:53.7080851Z       542 |         })
2021-03-26T15:19:53.7081586Z       543 |     })
2021-03-26T15:19:53.7082276Z       544 |   }
2021-03-26T15:19:53.7082700Z 
2021-03-26T15:19:53.7084324Z       at new <anonymous> (../node_modules/@adobe/aio-lib-core-errors/src/AioCoreSDKErrorWrapper.js:33:9)
2021-03-26T15:19:53.7086549Z       at fetchRetryClient.exponentialBackoff.then.catch.err (../src/index.js:541:18)
2021-03-26T15:19:53.7087846Z 
2021-03-26T15:19:53.7088691Z Test Suites: 1 failed, 1 total
2021-03-26T15:19:53.7091364Z Tests:       0 total
2021-03-26T15:19:53.7092193Z Snapshots:   0 total
2021-03-26T15:19:53.7093001Z Time:        66.359 s
```

**Comment by shazron** [comment]
cc @moritzraho
